### ISSUE TITLE
GPL license

### ISSUE THREAD

**Issue by tshort** [dvcrn/proton#11]
Why did you choose the GPL3 license? Most of the Atom ecosystem is MIT, so this choice limits sharing options. As an example, I'll avoid looking at your code for fear of "tainting" other packages.

**Comment by dvcrn** [comment]
MIT was the other option. I decided for GPL because I want to see proton to become a community managed open platform for atom. If someone makes an advancement, I want to see that get merged back at some point. The thing that I want to avoid is integration into closed source re-distributions (compiled js for example).

Parts that are meant to integrate with other plugins (later on) will definitely be MIT, but for the core I think GPL is the better choice. 

That being said, I am not a licensing export. If you have kick-ass reasons why to favour MIT here, I am pretty sure that with the current contributor count, a license change would almost definitely be possible.

**Comment by tshort** [comment]
Many companies stay away from GPL code because of the infectious nature of the license. This is especially true of JavaScript code because that often becomes distributed such that it would violate the GPL (it's compressed). Companies don't want to inadvertently violate someone's license by distributing "tainted" code. With MIT code (or similar), it's easier to maintain license compliance.

**Comment by dvcrn** [comment]
> this is especially true of JavaScript code because that often becomes distributed such that it would violate the GPL (it's compressed).

How so? Minifying or compressing code is not violating GPL. If you want to use GPL-ed code inside your project, you have to open source it. It's enough here if you can provide the source on request though. 

If you are worried about distributions of the binary or want to depend on it, we could think about LGPL but inclusion in closed source stuff is exactly why GPL was picked in the first place.
