### ISSUE TITLE
Using `SPC h/j/k/l` limits mnemonic categories

### ISSUE THREAD

**Issue by jessejanderson** [dvcrn/proton#146]
In Spacemacs these pane:focus keys are simply preceded with a `w` for a `window` category (`SPC w h` for 'focus left pane'.

There's an interesting problem right now with Proton in that you have to try and think ahead with categorizing so that you aren't having to change shortcuts all the time, messing with people who have learned them.

It would be great if categories could be planned out somewhat. For example - Spacemacs uses `SPC x` as the category for all text manipulation commands. I want to add a feature to sort lines of text so I was considering the following options:

1. `SPC x l s` (`leader => text manipulation => lines => sort`)
This matches Spacemacs, but feels slightly weird at this point since there is nothing else in the `lines` category or even the `text manipulation` category.

2. `SPC l s` (`leader => lines => sort`)
This makes a little more sense I think at this point, but `SPC l` is currently used for `pane:focus`

Maybe coming up with a future keybinding categories guide or something would be worthwhile so that keybindings don't end up getting changed as more features are added?

**Comment by dvcrn** [comment]
The decision to use h/j/k/l to move between panes was made deliberately. If I remember correctly, @geksilla removed it before but after a short discussion on the slack we decided to put it back in until the keys are needed. 

for `l` for example, I am not sure if having a `lines` category makes sense. I couldn't think of much more than sort lines for that category. If I were to categorise it, I would put it in:
- `SPC s` for selection, since it does something on a selection 
- `SPC b` for buffer since it works on the current buffer
- `SPC x` for text since it transforms text (as you said) 

Navigation is one of the most important actions inside the editor so having 3 strokes (`SPC w l`) instead of 2 (`SPC l`) is actually a big deal. Though I agree that we need to think about other ways to keep it efficient without blocking too many potential categories

**Comment by jessejanderson** [comment]
Okay, should I also change these shortcuts (https://github.com/dvcrn/proton/pull/144) to be simply `SPC H` for move pane left, etc? (or maybe in addition to?)

For the line sorting PR - there are 4 variations on the sorting (sort, reverse, unique, shuffle). Think something like this?

`SPC s s` (`leader => selection => sort`)
`SPC s r` (`leader => selection => reverse`)
`SPC s h` (`leader => selection => shuffle`)
`SPC s u` (`leader => selection => uniquify`)

I like this because, while selection makes sense, I can also just think of these particular commands as being under a sort category (`s s` sort selection, `s r` sort in reverse, `s h` shuffle, `s u` sort uniques).

**Comment by jessejanderson** [comment]
Agh, `SPC s` is already used for `search` category.

**Comment by dvcrn** [comment]
Closing this until we really need more categories :)

**Comment by richarddewit** [comment]
Since it's case sensitive, you could put this in <kbd>SPC S</kbd> (capital S) instead. More categories, yay! :)
