### ISSUE TITLE
"f" character in Insert mode is not printed immediately

### ISSUE THREAD

**Issue by TheGreenHabi** [dvcrn/proton#203]
Hello!
Just installed Atom + Proton to check it out and immediately run into issue when I type `f` character and it shows up only after I press some other character. I have this issue only with small `f`.
Perhaps it's a bug in ```fd``` implementation?

`My OS: Windows 10 + latest updates, Atom Beta (May 28, 2016) and current Proton version from built-in Atom package manager`

**Comment by TheGreenHabi** [comment]
Indeed it is. After I commented this line in `.proton` file
`;; {:selector "atom-text-editor.vim-mode-plus:not(.normal-mode)" :keymap [["f d" "vim-mode-plus:activate-normal-mode"]]}`
everything is fine

**Comment by dvcrn** [comment]
Yep, proton follows spacemacs (with it's default settings) in where `fd` doubles as esc alternative for vim related bindings. 

Because of how atom works, it needs to put a timeout on the first key. For it to get printed you need to either wait for the timeout to expire or hit any other key. 

If you don't need it just remove the line from the `.proton` file like you did 😄
