### ISSUE TITLE
Better default experience

### ISSUE THREAD

**Issue by dvcrn** [dvcrn/proton#23]
When I think about proton, I'm more thinking about a complete package: Something that you install that makes your editor instantly better while getting rid of annoying things. Similar to nuclide.

We should go over all settings atom provides and check which ones are useful by default and which ones don't make sense. Plus maybe adding toggles for them inside the `core` layer. 

I think including themes / fonts could also fall under this category. A beginning would be to ship Hack / Source Code Pro with proton and install a fresh template by default (thinking about https://atom.io/themes/atom-material-ui).

**Comment by spencerlyon2** [comment]
I definitely agree with providing a better default experience. I know a number of people who don't want to use atom simply because it takes to long to go from stock atom to something they like and feel is usable. 

One thing I think the spacemacs team got right was that they set a number of config values for you to give a pretty opinionated emacs dist, but most (all?) of these default config values can be overwritten by the user in `~/.spacemacs`. 

I suggest that we should feel free to be pretty specific in tuning the default proton template to be just what we the developers want to use (maybe toned down a little bit) *as long as* we allow users to undo any of the configurations we set. You've started this by having settings for `proton.core.(quickOpenProvider |relativeLineNumbers| showTabBar)`

**Comment by osdf** [comment]
So, I'm very excited about this, being a long-term vim (and now spacemacs) user. I really want to like atom/proton-mode, but after installing everything and starting up, shouldn't the space key be the central UI element? Hitting it after start-up does nothing, though. Maybe I'm doing something wrong? Btw, is there a gitter (or slack?) channel for proton-mode?

**Comment by dvcrn** [comment]
@osdf We have a #proton channel on the clojurians slack but right now there are only 3 people in there. 

Currently the space key works when you are in normal mode in your text editor. 
To debug why it doesn't work, do you get the proton prompt after installation? Which version do you have installed? Can you open the dev tools and check for any errors?

**Comment by dvcrn** [comment]
I'm closing this here. We seem to have a great default experience now :)
