### ISSUE TITLE
Esc in insert mode

### ISSUE THREAD

**Issue by kibin** [dvcrn/proton#232]
On today’s startup of atom I started to experience annoying thing that whenever I type something and then press escape, it doesn’t switch me to normal mode, as it always been, but only cancels autocomplete that pops up almost every time. So now I need to think hard to notice whether I need to press escape once or twice and it blows my mind.
Any known workarounds of this?

**Comment by alex-ketch** [comment]
@kibin After the 0.12 update I had to uninstall and re-install the `vim-mode-plus` package.
I'd give that a shot and see if it fixes anything.

Also make sure you follow the warning notification and update your `~/.proton` file to have
`["proton.core.inputProvider" :vim-mode-plus]` instead of `["proton.core.vim-provider" :vim-mode-plus]`

**Comment by kibin** [comment]
Uninstalling `vim-mode-plus` helped, thanks!
